driver=com.mysql.jdbc.Driver
url=jdbc:mysql://localhost:3306/c2c?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
username=root
password=
initiaSize=0
maxActive=20
maxIdle=20
minIdle=1
maxWait=60000